### ISSUE TITLE
Not loading any data file after loading file with wrong extension

### ISSUE THREAD

**Issue by maximelucas** [luphysics/PyMODA#3] opened 2020-02-08 19:59 UTC
After opening pyMODA, go the "Time-Frequency Analasis" module. The module window opens, together with a pop-up error window "addItems(self, Iterable[str]): argument 1 has unexpected type 'str'". 

This happened after I tried to load an .npy file as data file, and got an error such as "wrong format file". Now, I cannot use any of MODA's modules, because I always get the above error  "unexpected type" which prevents me from loading any valid data file.

I have tried restarting pyMODA, withouth success. Restarting my computer did not work either.

Here is the log from the terminal, when the error occurs:

```
maxime@maxime-ThinkPad-T450:~$ pymoda
Welcome to PyMODA. Please do not close this terminal window while PyMODA is running.
Calculation terminated.
Traceback (most recent call last):
  File "/home/maxime/Documents/pyMODA/src/gui/Application.py", line 43, in start_time_frequency
    self.open_window(TFWindow)
  File "/home/maxime/Documents/pyMODA/src/gui/Application.py", line 67, in open_window
    window = WindowType(self)
  File "/home/maxime/Documents/pyMODA/src/gui/windows/timefrequency/TFWindow.py", line 65, in __init__
    self.presenter.init()
  File "/home/maxime/Documents/pyMODA/src/gui/windows/common/BaseTFPresenter.py", line 59, in init
    self.view.select_file()
  File "/home/maxime/Documents/pyMODA/src/gui/windows/common/BaseTFWindow.py", line 54, in select_file
    file_path = SelectFileDialog().get_result()
  File "/home/maxime/Documents/pyMODA/src/gui/dialogs/files/SelectFileDialog.py", line 41, in __init__
    super().__init__()
  File "/home/maxime/Documents/pyMODA/src/gui/BaseUI.py", line 28, in __init__
    self.setup_ui()
  File "/home/maxime/Documents/pyMODA/src/gui/dialogs/files/SelectFileDialog.py", line 46, in setup_ui
    self.setup_recent_files()
  File "/home/maxime/Documents/pyMODA/src/gui/dialogs/files/SelectFileDialog.py", line 95, in setup_recent_files
    self.combo_recent.addItems(files)
TypeError: addItems(self, Iterable[str]): argument 1 has unexpected type 'str'
```

**Comment by spmccormack** [comment] 2020-02-09 10:23
Thanks for the useful bug report! 

There seem to be two parts to the problem:

1. Loading the `.npy` file causes an error.
2. This error causes an unexpected value to be saved to the preferences file, `settings.conf`, which causes future errors.

I believe I've managed to fix problem 2, which is causing the error message in the latter part of your post. You should be able to load other data files after updating the program (using Git or the [built-in updater](https://github.com/luphysics/PyMODA#updating-pymoda)). If the same issue persists, please delete `settings.conf` from the `pyMODA` folder and let me know if it occurs again.

As for problem 1, I can't reproduce this with my data files. Would you be able to send a link to the data file via [Firefox Send](https://send.firefox.com)? You can set the link to expire after 1 download, and can post the link here or email it to s.p.mccormack@lancaster.ac.uk.

**Comment by maximelucas** [comment] 2020-02-09 10:34
Great! After updating:
2. was fixed after deleting settings.conf. Recent files are listed without problem.
1. I cannot reproduce either, must be some error on my part

**Comment by spmccormack** [comment] 2020-02-09 10:40
Ok, that's good. I'll close this issue, but feel free to comment if there are any other bugs or problems with loading data files.

**Closed as completed** 2020-02-10 10:50 UTC
